apiVersion: apps/v1
kind: Deployment
metadata:
  name: laraval
  labels:
    app: laraval
spec:
  replicas: 2
  selector:
    matchLabels:
      app: laraval
  template:
    metadata:
      labels:
        app: laraval
    spec:
      containers:
      - name: laraval
        image: rajatb2/laravel-kubernetes:latest
        env:
        - name: APP_KEY
          value: "base64:mpSDVVAKfJXbJNV8U2tpdtOY7o0Kmk7OEKH64WvCOXA="
        ports:
        - containerPort: 80

